
ALTER TABLE `phoenix_npc_spawns`
    ADD COLUMN `presetId`   INT UNSIGNED NULL          AFTER `script`,
    ADD COLUMN `scaleX`     FLOAT        NOT NULL DEFAULT 1.0   AFTER `angle`,
    ADD COLUMN `scaleY`     FLOAT        NOT NULL DEFAULT 1.0   AFTER `scaleX`,
    ADD COLUMN `scaleZ`     FLOAT        NOT NULL DEFAULT 1.0   AFTER `scaleY`,
    ADD COLUMN `fatness`    FLOAT        NOT NULL DEFAULT 0.0   AFTER `scaleZ`,
    ADD COLUMN `hp`         INT          NOT NULL DEFAULT 0     AFTER `fatness`,
    ADD COLUMN `level`      INT          NOT NULL DEFAULT 0     AFTER `hp`,
    ADD COLUMN `strength`   INT          NOT NULL DEFAULT 0     AFTER `level`,
    ADD COLUMN `dexterity`  INT          NOT NULL DEFAULT 0     AFTER `strength`,
    ADD COLUMN `bodyModel`  VARCHAR(64)  NOT NULL DEFAULT ''    AFTER `dexterity`,
    ADD COLUMN `bodyTex`    INT          NOT NULL DEFAULT -1    AFTER `bodyModel`,
    ADD COLUMN `headModel`  VARCHAR(64)  NOT NULL DEFAULT ''    AFTER `bodyTex`,
    ADD COLUMN `headTex`    INT          NOT NULL DEFAULT -1    AFTER `headModel`,
    ADD COLUMN `voice`      INT          NOT NULL DEFAULT 0     AFTER `headTex`,
    ADD INDEX `idx_npc_spawns_preset` (`presetId`);

CREATE TABLE IF NOT EXISTS `phoenix_npc_presets` (
    `id`           INT UNSIGNED  NOT NULL AUTO_INCREMENT,
    `code`         VARCHAR(64)   NOT NULL,
    `label`        VARCHAR(128)  NOT NULL DEFAULT '',
    `instance`     VARCHAR(64)   NOT NULL,
    `category`     VARCHAR(32)   NOT NULL DEFAULT 'monster',
    `hostile`      TINYINT       NOT NULL DEFAULT 1,
    `respawnSec`   INT           NOT NULL DEFAULT 60,
    `scaleX`       FLOAT         NOT NULL DEFAULT 1.0,
    `scaleY`       FLOAT         NOT NULL DEFAULT 1.0,
    `scaleZ`       FLOAT         NOT NULL DEFAULT 1.0,
    `fatness`      FLOAT         NOT NULL DEFAULT 0.0,
    `hp`           INT           NOT NULL DEFAULT 0,
    `level`        INT           NOT NULL DEFAULT 0,
    `strength`     INT           NOT NULL DEFAULT 0,
    `dexterity`    INT           NOT NULL DEFAULT 0,
    `bodyModel`    VARCHAR(64)   NOT NULL DEFAULT '',
    `bodyTex`      INT           NOT NULL DEFAULT -1,
    `headModel`    VARCHAR(64)   NOT NULL DEFAULT '',
    `headTex`      INT           NOT NULL DEFAULT -1,
    `voice`        INT           NOT NULL DEFAULT 0,
    `metadata`     JSON          NULL,
    `createdBy`    INT UNSIGNED  NULL,
    `createdAt`    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updatedAt`    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_npc_presets_code` (`code`),
    KEY `idx_npc_presets_instance` (`instance`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
