CREATE TABLE IF NOT EXISTS `phoenix_houses` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `slug` VARCHAR(64) NOT NULL,
  `world` VARCHAR(64) NOT NULL DEFAULT 'NEWWORLD',
  `centerX` FLOAT NOT NULL DEFAULT 0,
  `centerY` FLOAT NOT NULL DEFAULT 0,
  `centerZ` FLOAT NOT NULL DEFAULT 0,
  `minX` FLOAT NOT NULL DEFAULT 0,
  `minY` FLOAT NOT NULL DEFAULT 0,
  `minZ` FLOAT NOT NULL DEFAULT 0,
  `maxX` FLOAT NOT NULL DEFAULT 0,
  `maxY` FLOAT NOT NULL DEFAULT 0,
  `maxZ` FLOAT NOT NULL DEFAULT 0,
  `cornersJson` TEXT NULL,
  `metadataJson` TEXT NULL,
  `entryX` FLOAT NULL,
  `entryY` FLOAT NULL,
  `entryZ` FLOAT NULL,
  `entryHeading` FLOAT NULL,
  `ownerType` TINYINT(4) NULL,
  `ownerId` INT(11) NULL,
  `priceGold` INT(11) NOT NULL DEFAULT 0,
  `weeklyRentGold` INT(11) NOT NULL DEFAULT 0,
  `rentPaidUntil` INT(11) NOT NULL DEFAULT 0,
  `guestAccountIds` TEXT NULL,
  `color` VARCHAR(9) NULL,
  `modeId` INT(11) NOT NULL DEFAULT 0,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  `createdBy` INT(11) NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `house_slug_unique` (`slug`),
  KEY `house_world_idx` (`world`),
  KEY `house_owner_idx` (`ownerType`, `ownerId`),
  KEY `house_active_idx` (`active`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;