local function w(value, dmg, dtype, range, reqs) {
	return {
		category    = PhoenixItemCategory.Weapon1H,
		slot        = PhoenixItemSlot.MainHand,
		value       = value,
		damage      = dmg,
		damageType  = dtype,
		requirement = reqs
	}
}

phoenix.item.register("ITMW_1H_BAU_AXE"                     , w(   10,    7, PhoenixDamageType.Edge      ,   50, [{ attr = "strength",  value = 5 }]))
phoenix.item.register("ITMW_1H_BAU_MACE"                    , w(    1,   10, PhoenixDamageType.Blunt     ,   70, [{ attr = "strength",  value = 10 }]))
phoenix.item.register("ITMW_1H_BLESSED_01"                  , w( 2000,  100, PhoenixDamageType.Edge      ,  100, [{ attr = "strength",  value = 100 }]))
phoenix.item.register("ITMW_1H_BLESSED_02"                  , w( 3000,  120, PhoenixDamageType.Edge      ,  100, [{ attr = "strength",  value = 100 }]))
phoenix.item.register("ITMW_1H_BLESSED_03"                  , w( 4000,  140, PhoenixDamageType.Edge      ,  100, [{ attr = "strength",  value = 100 }]))
phoenix.item.register("ITMW_1H_COMMON_01"                   , w(  450,   40, PhoenixDamageType.Edge      ,   90, [{ attr = "strength",  value = 30 }]))
phoenix.item.register("ITMW_1H_FERROSSWORD_MIS"             , w( 1200,  100, PhoenixDamageType.Edge      ,   90, [{ attr = "strength",  value = 80 }]))
phoenix.item.register("ITMW_1H_MACE_L_01"                   , w(    5,    5, PhoenixDamageType.Edge      ,   50, [{ attr = "strength",  value = 5 }]))
phoenix.item.register("ITMW_1H_MACE_L_03"                   , w(    5,    8, PhoenixDamageType.Blunt     ,   70, [{ attr = "strength",  value = 10 }]))
phoenix.item.register("ITMW_1H_MACE_L_04"                   , w(  200,   20, PhoenixDamageType.Blunt     ,   30, [{ attr = "strength",  value = 10 }]))
phoenix.item.register("ITMW_1H_MIL_SWORD"                   , w(   50,   40, PhoenixDamageType.Edge      ,   90, [{ attr = "strength",  value = 40 }]))
phoenix.item.register("ITMW_1H_MISC_AXE"                    , w(   40,   40, PhoenixDamageType.Edge      ,   80, [{ attr = "strength",  value = 40 }]))
phoenix.item.register("ITMW_1H_MISC_SWORD"                  , w(   30,   30, PhoenixDamageType.Edge      ,   70, [{ attr = "strength",  value = 30 }]))
phoenix.item.register("ITMW_1H_NOV_MACE"                    , w(  500,   30, PhoenixDamageType.Blunt     ,  130, [{ attr = "strength",  value = 15 }]))
phoenix.item.register("ITMW_1H_PAL_SWORD"                   , w(  600,   60, PhoenixDamageType.Edge      ,   70, [{ attr = "strength",  value = 60 }]))
phoenix.item.register("ITMW_1H_SLD_AXE"                     , w(   40,   40, PhoenixDamageType.Edge      ,   70, [{ attr = "strength",  value = 50 }]))
phoenix.item.register("ITMW_1H_SLD_SWORD"                   , w(   40,   40, PhoenixDamageType.Edge      ,   70, [{ attr = "strength",  value = 50 }]))
phoenix.item.register("ITMW_1H_SPECIAL_01"                  , w(  750,   60, PhoenixDamageType.Edge      ,   90, [{ attr = "strength",  value = 40 }]))
phoenix.item.register("ITMW_1H_SPECIAL_02"                  , w( 1200,  100, PhoenixDamageType.Edge      ,   90, [{ attr = "strength",  value = 80 }]))
phoenix.item.register("ITMW_1H_SPECIAL_03"                  , w( 1500,  140, PhoenixDamageType.Edge      ,  100, [{ attr = "strength",  value = 120 }]))
phoenix.item.register("ITMW_1H_SPECIAL_04"                  , w( 1800,  160, PhoenixDamageType.Edge      ,  100, [{ attr = "strength",  value = 140 }]))
phoenix.item.register("ITMW_1H_SWORD_L_03"                  , w(  250,   20, PhoenixDamageType.Edge      ,   30, [{ attr = "strength",  value = 10 }]))
phoenix.item.register("ITMW_1H_VLK_AXE"                     , w(  200,   20, PhoenixDamageType.Edge      ,   50, [{ attr = "strength",  value = 10 }]))
phoenix.item.register("ITMW_1H_VLK_DAGGER"                  , w(    5,    5, PhoenixDamageType.Edge      ,   50, [{ attr = "strength",  value = 5 }]))
phoenix.item.register("ITMW_1H_VLK_MACE"                    , w(   10,    8, PhoenixDamageType.Blunt     ,   70, [{ attr = "strength",  value = 5 }]))
phoenix.item.register("ITMW_1H_VLK_SWORD"                   , w(  500,   40, PhoenixDamageType.Edge      ,   70, [{ attr = "dexterity", value = 20 }]))
phoenix.item.register("ITMW_ADDON_BANDITTRADER"             , w(  250,   40, PhoenixDamageType.Edge      ,   70, [{ attr = "dexterity", value = 20 }]))
phoenix.item.register("ITMW_ADDON_BETTY"                    , w( 1300,  130, PhoenixDamageType.Edge      ,  100, [{ attr = "dexterity", value = 110 }]))
phoenix.item.register("ITMW_ADDON_HACKER_1H_01"             , w( 1100,  100, PhoenixDamageType.Edge      ,   75, [{ attr = "strength",  value = 90 }]))
phoenix.item.register("ITMW_ADDON_HACKER_1H_02"             , w(  600,   60, PhoenixDamageType.Edge      ,   70, [{ attr = "strength",  value = 60 }]))
phoenix.item.register("ITMW_ADDON_KEULE_1H_01"              , w(   25,   15, PhoenixDamageType.Blunt     ,   65, [{ attr = "strength",  value = 25 }]))
phoenix.item.register("ITMW_ADDON_KNIFE01"                  , w(  350,   30, PhoenixDamageType.Edge      ,   30, [{ attr = "strength",  value = 10 }]))
phoenix.item.register("ITMW_ADDON_PIR1HAXE"                 , w(  600,   60, PhoenixDamageType.Edge      ,   60, [{ attr = "strength",  value = 60 }]))
phoenix.item.register("ITMW_ADDON_PIR1HSWORD"               , w(  600,   60, PhoenixDamageType.Edge      ,   70, [{ attr = "strength",  value = 60 }]))
phoenix.item.register("ITMW_ALRIKSSWORD_MIS"                , w(   50,   30, PhoenixDamageType.Edge      ,   70, [{ attr = "strength",  value = 30 }]))
phoenix.item.register("ITMW_BARTAXT"                        , w(  900,   90, PhoenixDamageType.Edge      ,   70, [{ attr = "strength",  value = 90 }]))
phoenix.item.register("ITMW_DOPPELAXT"                      , w(  900,   90, PhoenixDamageType.Edge      ,   70, [{ attr = "strength",  value = 90 }]))
phoenix.item.register("ITMW_ELBASTARDO"                     , w( 1300,  120, PhoenixDamageType.Edge      ,  100, [{ attr = "strength",  value = 110 }]))
phoenix.item.register("ITMW_FOLTERAXT"                      , w( 1250,  125, PhoenixDamageType.Edge      ,   80, [{ attr = "strength",  value = 125 }]))
phoenix.item.register("ITMW_FRANCISDAGGER_MIS"              , w(    0,    5, PhoenixDamageType.Edge      ,   50, [{ attr = "strength",  value = 5 }]))
phoenix.item.register("ITMW_INQUISITOR"                     , w( 1100,  110, PhoenixDamageType.Edge      ,   60, [{ attr = "strength",  value = 110 }]))
phoenix.item.register("ITMW_KRIEGSHAMMER1"                  , w(  550,   55, PhoenixDamageType.Blunt     ,   40, [{ attr = "strength",  value = 55 }]))
phoenix.item.register("ITMW_KRIEGSHAMMER2"                  , w( 1200,  120, PhoenixDamageType.Blunt     ,   60, [{ attr = "strength",  value = 120 }]))
phoenix.item.register("ITMW_KRIEGSKEULE"                    , w(  500,   50, PhoenixDamageType.Blunt     ,   50, [{ attr = "strength",  value = 50 }]))
phoenix.item.register("ITMW_MALETHSGEHSTOCK_MIS"            , w(   10,    8, PhoenixDamageType.Blunt     ,   70, [{ attr = "strength",  value = 5 }]))
phoenix.item.register("ITMW_MEISTERDEGEN"                   , w( 2400,  120, PhoenixDamageType.Edge      ,  100, [{ attr = "dexterity", value = 60 }]))
phoenix.item.register("ITMW_MORGENSTERN"                    , w(  900,   90, PhoenixDamageType.Blunt     ,   60, [{ attr = "strength",  value = 90 }]))
phoenix.item.register("ITMW_NAGELKEULE"                     , w(  450,   40, PhoenixDamageType.Blunt     ,   70, [{ attr = "strength",  value = 30 }]))
phoenix.item.register("ITMW_NAGELKEULE2"                    , w(  600,   60, PhoenixDamageType.Blunt     ,   60, [{ attr = "strength",  value = 60 }]))
phoenix.item.register("ITMW_NAGELKNUEPPEL"                  , w(   50,   25, PhoenixDamageType.Blunt     ,   60, [{ attr = "strength",  value = 10 }]))
phoenix.item.register("ITMW_ORKSCHLAECHTER"                 , w( 1300,  130, PhoenixDamageType.Edge      ,  100, [{ attr = "strength",  value = 130 }]))
phoenix.item.register("ITMW_PIRATENSAEBEL"                  , w(  700,   65, PhoenixDamageType.Edge      ,   70, [{ attr = "strength",  value = 60 }]))
phoenix.item.register("ITMW_RABENSCHNABEL"                  , w( 1100,  110, PhoenixDamageType.Blunt     ,   60, [{ attr = "strength",  value = 110 }]))
phoenix.item.register("ITMW_RAPIER"                         , w( 2000,  100, PhoenixDamageType.Edge      ,   70, [{ attr = "dexterity", value = 50 }]))
phoenix.item.register("ITMW_RUBINKLINGE"                    , w( 1200,  100, PhoenixDamageType.Edge      ,   70, [{ attr = "strength",  value = 90 }]))
phoenix.item.register("ITMW_RUNENSCHWERT"                   , w( 1100,  110, PhoenixDamageType.Edge      ,   90, [{ attr = "strength",  value = 110 }]))
phoenix.item.register("ITMW_SCHIFFSAXT"                     , w(  600,   60, PhoenixDamageType.Edge      ,   70, [{ attr = "strength",  value = 60 }]))
phoenix.item.register("ITMW_SCHWERT"                        , w(  650,   65, PhoenixDamageType.Edge      ,   90, [{ attr = "strength",  value = 65 }]))
phoenix.item.register("ITMW_SCHWERT1"                       , w(  750,   60, PhoenixDamageType.Edge      ,   70, [{ attr = "strength",  value = 50 }]))
phoenix.item.register("ITMW_SCHWERT2"                       , w(  850,   85, PhoenixDamageType.Edge      ,   90, [{ attr = "strength",  value = 85 }]))
phoenix.item.register("ITMW_SCHWERT3"                       , w(  850,   90, PhoenixDamageType.Edge      ,  100, [{ attr = "strength",  value = 95 }]))
phoenix.item.register("ITMW_SCHWERT4"                       , w(  900,   80, PhoenixDamageType.Edge      ,   90, [{ attr = "strength",  value = 70 }]))
phoenix.item.register("ITMW_SCHWERT5"                       , w( 1100,  110, PhoenixDamageType.Edge      ,  100, [{ attr = "strength",  value = 110 }]))
phoenix.item.register("ITMW_SENSE"                          , w(  250,   25, PhoenixDamageType.Edge      ,   60, [{ attr = "strength",  value = 10 }]))
phoenix.item.register("ITMW_SHORTSWORD1"                    , w(  250,   20, PhoenixDamageType.Edge      ,   50, [{ attr = "strength",  value = 10 }]))
phoenix.item.register("ITMW_SHORTSWORD2"                    , w(  250,   20, PhoenixDamageType.Edge      ,   50, [{ attr = "strength",  value = 10 }]))
phoenix.item.register("ITMW_SHORTSWORD3"                    , w(  500,   40, PhoenixDamageType.Edge      ,   50, [{ attr = "strength",  value = 20 }]))
phoenix.item.register("ITMW_SHORTSWORD4"                    , w(  550,   45, PhoenixDamageType.Edge      ,   50, [{ attr = "strength",  value = 22 }]))
phoenix.item.register("ITMW_SHORTSWORD5"                    , w(  750,   50, PhoenixDamageType.Edge      ,   50, [{ attr = "strength",  value = 25 }]))
phoenix.item.register("ITMW_SPICKER"                        , w(  700,   70, PhoenixDamageType.Blunt     ,   60, [{ attr = "strength",  value = 70 }]))
phoenix.item.register("ITMW_STEINBRECHER"                   , w(  800,   80, PhoenixDamageType.Blunt     ,   50, [{ attr = "strength",  value = 80 }]))
phoenix.item.register("ITMW_STREITKOLBEN"                   , w( 1000,  100, PhoenixDamageType.Blunt     ,   60, [{ attr = "strength",  value = 100 }]))

