(function (global) {
	// Mapping: NPC instance -> body model mesh file (from data.xml <body_model>)
	// Monsters only; humanoids are excluded from bestiary so no need here.
	const NPC_VISUALS = {
		WOLF: "WOL_BODY.MDM",
		YWOLF: "WOL_BODY.MDM",
		SUMMONED_WOLF: "WOL_BODY.MDM",
		BLACKWOLF: "WARG_BODY.MDM",
		WARG: "WARG_BODY2.MDM",
		ICEWOLF: "SNOWOL_BODY.MDM",
		PEPES_YWOLF1: "WOL_BODY.MDM",
		PEPES_YWOLF2: "WOL_BODY.MDM",
		PEPES_YWOLF3: "WOL_BODY.MDM",
		PEPES_YWOLF4: "WOL_BODY.MDM",

		KEILER: "KEI_BODY.MDM",
		GIANT_RAT: "GRAT_BODY.MDM",
		GIANT_BUG: "SHA_BODY.MDM",
		MEATBUG: "MBG_BODY.MDM",
		MEATBUG_BRUTUS1: "MBG_BODY.MDM",
		MEATBUG_BRUTUS2: "MBG_BODY.MDM",
		MEATBUG_BRUTUS3: "MBG_BODY.MDM",
		MEATBUG_BRUTUS4: "MBG_BODY.MDM",
		MOLERAT: "MRAT_BODY.MDM",

		SCAVENGER: "SCA_BODY.MDM",
		SCAVENGER_DEMON: "SCA_BODY.MDM",
		BLOODHOUND: "BHN_BODY.MDM",
		BLOODFLY: "BFLY_BODY.MDM",
		YBLOODFLY: "BFLY_BODY.MDM",

		MINECRAWLER: "MCR_BODY.MDM",
		MINECRAWLER_PRIEST: "MCRP_BODY.MDM",
		MINECRAWLER_WARRIOR: "MCR_BODY.MDM",

		WARAN: "WAR_BODY.MDM",
		FIREWARAN: "WAR_BODY.MDM",
		LURKER: "LUR_BODY.MDM",
		SNAPPER: "SNA_BODY.MDM",
		DRAGONSNAPPER: "DSN_BODY.MDM",
		SWAMPSHARK: "SSH_BODY.MDM",

		ZOMBIE: "ZOM_BODY.MDM",
		SWAMPZOMBIE: "ZSW_BODY.MDM",
		SKELETON: "SKE_BODY.MDM",
		LESSER_SKELETON: "SKE_BODY.MDM",
		GOBBO_SKELETON: "GOBS_BODY.MDM",
		SHADOWBEAST: "SHA_BODY.MDM",
		SHADOWBEAST_SKELETON: "SHA_BODY_SKELETON.MDM",

		TROLL: "TRO_BODY.MDM",
		VALLEY_TROLL: "TRO_BODY.MDM",
		MAYA_TROLL: "TRO_BODY.MDM",
		TROLL_DI: "TRO_BODY.MDM",
		TROLL_BLACK: "TROLL_BLACK_BODY.MDM",

		ORCBITER: "SC2_BODY.MDM",
		GOBBO_GREEN: "GOB_BODY.MDM",
		GOBBO_BLACK: "GOB_BODY.MDM",

		DRAGON_FIRE: "DRAGON_FIRE_BODY.MDM",
		DRAGON_ICE: "DRAGON_ICE_BODY.MDM",
		DRAGON_ROCK: "DRAGON_ROCK_BODY.MDM",
		DRAGON_SWAMP: "DRAGON_SWAMP_BODY.MDM",
		DRAGON_UNDEAD: "DRAGON_UNDEAD_BODY.MDM"
	};

	global.PhoenixNpcVisuals = {
		get: function (instance) {
			if (!instance) return "";
			const key = String(instance).toUpperCase();
			return NPC_VISUALS[key] || "";
		},
		all: function () { return NPC_VISUALS; }
	};
})(typeof window !== "undefined" ? window : globalThis);
